# Generated by Django 5.2 on 2025-05-03 15:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QLearningAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='QLearningState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RankingConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('learning_rate', models.FloatField(default=0.1)),
                ('discount_factor', models.FloatField(default=0.9)),
                ('exploration_rate', models.FloatField(default=0.3)),
                ('quality_weight', models.FloatField(default=0.25)),
                ('delivery_weight', models.FloatField(default=0.25)),
                ('price_weight', models.FloatField(default=0.25)),
                ('service_weight', models.FloatField(default=0.25)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RankingEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('RANKING_STARTED', 'Ranking Process Started'), ('RANKING_COMPLETED', 'Ranking Process Completed'), ('MODEL_TRAINED', 'Q-Learning Model Trained'), ('RECOMMENDATION_MADE', 'Supplier Recommendation Made'), ('DATA_FETCHED', 'External Data Fetched'), ('ERROR', 'Error Occurred')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField()),
                ('supplier_id', models.IntegerField(blank=True, null=True)),
                ('state_id', models.IntegerField(blank=True, null=True)),
                ('action_id', models.IntegerField(blank=True, null=True)),
                ('reward', models.FloatField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SupplierPerformanceCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(help_text='ID reference to Supplier in User Service')),
                ('supplier_name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('quality_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('defect_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('return_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('on_time_delivery_rate', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('average_delay_days', models.FloatField(default=0)),
                ('price_competitiveness', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('responsiveness', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('issue_resolution_time', models.FloatField(blank=True, help_text='Average time to resolve issues in hours', null=True)),
                ('fill_rate', models.FloatField(help_text='Percentage of order quantities fulfilled', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('order_accuracy', models.FloatField(help_text='Percentage of orders with correct items', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('compliance_score', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('demand_forecast_accuracy', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('logistics_efficiency', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('data_complete', models.BooleanField(default=False)),
            ],
            options={
                'unique_together': {('supplier_id', 'date')},
            },
        ),
        migrations.CreateModel(
            name='QTableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_value', models.FloatField(default=0.0)),
                ('update_count', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_values', to='api.qlearningaction')),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='q_values', to='api.qlearningstate')),
            ],
            options={
                'unique_together': {('state', 'action')},
            },
        ),
        migrations.CreateModel(
            name='SupplierRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier_id', models.IntegerField(default=0, help_text='ID reference to Supplier in User Service')),
                ('supplier_name', models.CharField(default='Unknown Supplier', help_text='Cached supplier name for display purposes', max_length=255)),
                ('date', models.DateField()),
                ('overall_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('quality_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('delivery_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('price_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('service_score', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('rank', models.IntegerField(help_text='Rank position among all suppliers')),
                ('notes', models.TextField(blank=True, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supplier_rankings', to='api.qlearningstate')),
            ],
            options={
                'unique_together': {('supplier_id', 'date')},
            },
        ),
    ]
