# Generated by Django 5.2 on 2025-05-07 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplierranking',
            name='tier',
            field=models.IntegerField(default=3, help_text='Supplier tier level (1-3, with 1 being highest)'),
        ),
    ]
